#! /usr/bin/env bash

#### Copy all output to log file.
log=install.$$.log
echo "Recording log in $log ..."
exec > >(tee $log) # Requires fdescfs mounted to /dev/fd on FreeBSD.
exec 2>&1

mdir="/opt/llvm"

src="$mdir/src/clang-chimera"
build="$mdir/build/clang-chimera"

mkdir -p $src 
mkdir -p $build

# clone chimera repository

git clone https://github.com/ntonjeta/clang-chimera $src 

(cmake $src)
