#! /usr/bin/env bash

#### Copy all output to log file.
log=install.$$.log
echo "Recording log in $log ..."
exec > >(tee $log) # Requires fdescfs mounted to /dev/fd on FreeBSD.
exec 2>&1


git clone https://github.com/ntonjeta/Bellerophon
cd Bellerophon
mkdir build
cd build
cmake ../ 
make


